"""Add WorkloadTemplate model

Revision ID: 48d54324b034
Revises: b92f8e5c6983
Create Date: 2026-01-07 02:39:07.224865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '48d54324b034'
down_revision = 'b92f8e5c6983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('workload_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('academic_year_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.Integer(), nullable=False),
    sa.Column('distribution_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['workload_id'], ['workload.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workload_id', 'group_id', 'semester', name='unique_workload_template')
    )
    op.drop_table('generation_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('academic_year_id', sa.INTEGER(), nullable=False),
    sa.Column('semester', sa.INTEGER(), nullable=True),
    sa.Column('algorithm', sa.VARCHAR(length=20), nullable=True),
    sa.Column('generation_mode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('max_consecutive_pairs', sa.INTEGER(), nullable=True),
    sa.Column('preferred_days', sqlite.JSON(), nullable=True),
    sa.Column('time_slots', sqlite.JSON(), nullable=True),
    sa.Column('excluded_times', sqlite.JSON(), nullable=True),
    sa.Column('repeat_interval', sa.VARCHAR(length=20), nullable=True),
    sa.Column('avoid_gaps', sa.BOOLEAN(), nullable=True),
    sa.Column('balance_daily_load', sa.BOOLEAN(), nullable=True),
    sa.Column('respect_teacher_preferences', sa.BOOLEAN(), nullable=True),
    sa.Column('follow_gup', sa.BOOLEAN(), nullable=True),
    sa.Column('room_preference_weight', sa.INTEGER(), nullable=True),
    sa.Column('teacher_workload_weight', sa.INTEGER(), nullable=True),
    sa.Column('student_convenience_weight', sa.INTEGER(), nullable=True),
    sa.Column('gap_avoidance_weight', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workload_templates')
    # ### end Alembic commands ###
